# Generated by Django 5.1.4 on 2024-12-16 06:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0003_listing_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_offers_received', to=settings.AUTH_USER_MODEL)),
                ('receiver_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_trades', to='trades.listing')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_offers_sent', to=settings.AUTH_USER_MODEL)),
                ('sender_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_trades', to='trades.listing')),
            ],
        ),
    ]
