# Generated by Django 5.1.4 on 2024-12-16 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0004_trade'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='chat_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
