# Generated by Django 5.1.4 on 2025-02-19 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0006_rename_chat_message_trade_negotiation_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='counter_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trades.listing'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='receiver_listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_listings', to='trades.listing'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='sender_listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_listings', to='trades.listing'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('negotiation', 'Negotiation'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
