# Generated by Django 5.1.4 on 2025-02-22 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0007_alter_trade_counter_offer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='is_skill',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='stock',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
