# Generated by Django 5.1.4 on 2025-02-22 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0008_listing_is_skill_listing_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='latitude',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='longitude',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='latitude',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='longitude',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='location',
            field=models.CharField(blank=True, default='Unknown Location', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, default='Unknown Location', max_length=255),
        ),
    ]
