# Generated by Django 5.1.4 on 2025-03-25 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0009_listing_latitude_listing_longitude_profile_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='country',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
