# Generated by Django 5.1.7 on 2025-03-28 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0014_remove_listing_is_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='condition',
            field=models.CharField(choices=[('new', 'New'), ('used', 'Used'), ('damaged', 'Damaged')], default='unspecified', max_length=10),
        ),
    ]
