# Generated by Django 5.1.7 on 2025-03-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0016_userwishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='tag',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='listing',
            name='condition',
            field=models.CharField(choices=[('new', 'New'), ('used', 'Used'), ('damaged', 'Damaged')], default='used', max_length=10),
        ),
    ]
