# Generated by Django 5.1.7 on 2025-03-28 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0017_listing_tag_alter_listing_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='interests',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
