# Generated by Django 5.1.7 on 2025-03-29 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0018_profile_interests'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('info', 'Info'), ('match', 'Match')], default='info', max_length=10),
        ),
    ]
