# Generated by Django 5.1.7 on 2025-03-29 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0019_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('trade', 'Trade'), ('match', 'Interest Match'), ('system', 'System')], default='system', max_length=20),
        ),
    ]
