# Generated by Django 5.1.7 on 2025-03-29 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0025_profile_is_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='business_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='offer_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='skills_hiring_for',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
