# Generated by Django 5.1.7 on 2025-03-29 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0026_profile_business_name_profile_offer_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='is_business_listing',
            field=models.BooleanField(default=False),
        ),
    ]
