# Generated by Django 5.1.7 on 2025-03-29 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0027_listing_is_business_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='offer_tag',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
