# Generated by Django 5.1.7 on 2025-03-29 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0029_trade_rejected_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeclinedBusinessSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('business_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declined_business', to='trades.listing')),
                ('user_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declined_user', to='trades.listing')),
            ],
            options={
                'unique_together': {('business_listing', 'user_listing')},
            },
        ),
    ]
