# Generated by Django 5.1.7 on 2025-03-30 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0030_declinedbusinessskill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='tag',
            field=models.CharField(blank=True, choices=[('music', 'Music'), ('home_services', 'Home Services'), ('crafting', 'Crafting'), ('teaching', 'Teaching'), ('fitness', 'Fitness'), ('design', 'Design'), ('language_help', 'Language Help'), ('food', 'Food'), ('clothing', 'Clothing'), ('tech', 'Tech'), ('pets', 'Pets'), ('toys', 'Toys'), ('books', 'Books'), ('furniture', 'Furniture'), ('decor', 'Decor')], max_length=100, null=True),
        ),
    ]
