# Generated by Django 5.1.7 on 2025-03-30 21:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0031_alter_listing_tag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='completed_by',
            field=models.ManyToManyField(blank=True, related_name='completed_trades', to=settings.AUTH_USER_MODEL),
        ),
    ]
